audit_header: false
title: "Guaranteed Offer"
description: Ed Pluchar, a top Real Estate Agent in the Greater Joliet Area, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
client:
  name: Ed Pluchar
  title:
  license_number:
  about_markdown: |

  market: Greater Joliet Area
  brand: Real People Realty
  brokerage:
  address: 9981 W 190th Street Suite H | Mokena, IL | 60448 US
  phone: 815-931-2279
  phone_type:
  phone2:
  phone2_type:
  email: ed@thepluchargroup.com
  url: http://www.houseandkeys.com/blog

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#a31437'
  theme_color: '#231f20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
